### ISSUE TITLE
optimization is taking too long

### ISSUE THREAD

**Issue by johannes-graeter** [johannes-graeter/limo#12]
@johannes-graeter No, I don't think there is any error output, except for the very beginning when it complains about `sensor/camera` frame can't be found. I capture my screen [here](https://youtu.be/xO6ik85WNyI).

The final screenshot is like this:
![ask_limo2](https://user-images.githubusercontent.com/18464308/47656035-96676e80-db8e-11e8-9ccd-cdbc35721f84.png)
So is this the expected output?

_Originally posted by @tuandle in https://github.com/johannes-graeter/limo/issues/8#issuecomment-433929329_

**Comment by johannes-graeter** [comment]
thanks for the screencast, that was helpful.
so the problem is that even though the specs of your computer look ok, the optimization for the full bundle adjustment each time a keyframe is chosen takes way too long (around 1 sec which is 4 times more than on my computer with similar specs). That's why after a while queues of the rosnodes overflow and data gets lost... This is a bit hard to debug from remote though... First thing you can check is if ceres is build in release mode. Did you build it on your machine or did you use the prebuilts from apt-get install? We'll get to it ;)

**Comment by tuandle** [comment]
@johannes-graeter thanks for your fast reply. I built ceres from source quite some time ago and I can't remember if I built it in release mode. Nonetheless, I uninstalled and rebuilt ceres with `-DCMAKE_BUILD_TYPE=Release` flag (I am not sure if it has any effect since the current installation guide doesn't mention it). I also `catkin clean` the workspace and rebuild everything but the problem still persists.

**Comment by tuandle** [comment]
@johannes-graeter I decided to switch to a desktop computer and I have converged solutions from ceres. I am not sure what went wrong with my laptop but the problem definitely not from the package. 
The final result looks fine! Thanks again! I guess I have to do a fresh install on my laptop.
![ask_limo3](https://user-images.githubusercontent.com/18464308/47664974-67f28f00-dba0-11e8-99a9-96be0cad8f4d.png)

**Comment by johannes-graeter** [comment]
Cool! Thanks for making it work!
If you know the issue please share :) 
If you have some experience with the system I would be happy to know what works, what doesn't (people tend to give feedback on setup issues, but I haven't had feedback on a working setup yet ;) )

**Comment by KleinYuan** [comment]
I have met the same issue:
- at the first place, it worked
- after I installed other packages, which potentially touches glog and gflags, which are all important dependencies for ceres, I observed the issue happened
- then, I nuked the workspace and reinstalled the ceres&limo, the issue is gone

**Comment by johannes-graeter** [comment]
@KleinYuan Thanks for trying out my stuff :) 
IN order to get a hold of the issue, could you try out the docker container and install the packages that conflicted in that clean environment, so we can make it repdoucible? Otherwise debugging will be quite hard

**Comment by KleinYuan** [comment]
Unfortunately, the docker seems not working for me. The feature tracking repo has some broken changes, which pbbly shall be fixed for the docked image first.

I can try the docker later after I wrap up my current on-going project (on a ddl), to verify the RC.

**Comment by johannes-graeter** [comment]
seems to work for others, closing until issue pops up again
