### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by MaxCCao** [johannes-graeter/limo#13]
Hello,thank u for sharing your project !!!
But when i followed your instruction, i got some problems.
after  "bash install_repos.sh" , i got this
![build](https://user-images.githubusercontent.com/44768876/48397163-d8c8a800-e757-11e8-8567-439e2046e41c.png)
after "catkin run_tests --profile limo_release" , i got this
![test](https://user-images.githubusercontent.com/44768876/48397185-ee3dd200-e757-11e8-8ebb-dd7757149fab.png)

Here are the details:
Errors     << keyframe_bundle_adjustment:make /home/cqu123/workspace/logs_limo_release/keyframe_bundle_adjustment/build.make.002.log
Failed     << keyframe_bundle_adjustment:make                     [ Exited with code 2 ]
Failed    <<< keyframe_bundle_adjustment                          [ 1.1 seconds ]
Abandoned <<< image_preproc_ros_tool                              [ Unrelated job failed ]
Abandoned <<< matches_conversion_ros_tool                         [ Unrelated job failed ]
Abandoned <<< util_nodes_tf2_ros_tool                             [ Unrelated job failed ]
Abandoned <<< tracklets_depth_ros_tool                            [ Unrelated job failed ]
Abandoned <<< viso_feature_tracking_ros_tool                      [ Unrelated job failed ]
Abandoned <<< keyframe_bundle_adjustment_ros_tool                 [ Unrelated job failed ]
Abandoned <<< demo_keyframe_bundle_adjustment_meta                [ Unrelated job failed ]

i have installed all the requirements include ceres before build
i'll appreciate if you can reply !

**Comment by johannes-graeter** [comment]
Hi,

thanks for the interest in my work!

So what you are saying is that the project build correctly, but the unittests failed.
could you dump the output of 
"catkin run_tests --profile limo_release > unittests_dump.txt" and upload it here in the issue?

Regards,

Johannes

**Comment by MaxCCao** [comment]
[unittests_dump.txt](https://github.com/johannes-graeter/limo/files/2575315/unittests_dump.txt)

Thanks for your reply,
Max

**Comment by johannes-graeter** [comment]
I can't reproduce the error, on my machine it works fine with a fresh install in a clean environment.
The problem arises in the landmark selection module which uses the pcl library for building a voxel grid for thinning out landmarks. 
Perhaps you are using a different pcl version than me.

Can you post the output of dpkg -l "*libpcl*" ?

**Comment by johannes-graeter** [comment]
Ok, I repdroduced the error on my machine. 
Problem is that I used a newer version of libpcl (1.8.1) than in the ros repos of ros kinetic (1.7.2).
However for the performance of the algorithm that should not be an issue. 
Ignore the unittest error for now and try running it as described in the README.md

Looking forward to hear your feedback.

Regards

**Comment by MaxCCao** [comment]
thanks, i will try it later and then post the result :)

**Comment by MaxCCao** [comment]
Hi, i find out that the libpcl i use is  1.7.2, as the terminal shows: " libpcl-dev is already the newest version (1.7.2-14build1) " . 
However i ignored the unittest error and ran it as the README.md described.
When " source ${your_catkin_workspace}/devel_limo_release/setup.sh " , it didn't work , so i think maybe it should be " source setup.bash "
When " roslaunch demo_keyframe_bundle_adjustment_meta kitti_standalone.launch ", it worked but with one error:
[ERROR] [1542177300.194857513]: "sensor/camera" passed to lookupTransform argument target_frame does not exist. 
When rviz, i wondered which fix frames should i select ?
![rviz](https://user-images.githubusercontent.com/44768876/48464930-26a6e400-e81c-11e8-908f-7387cf94d7db.png)
Thanks again

**Comment by johannes-graeter** [comment]
For the plotting open the .rviz file that is supplied in demo_keyframe_bundle_adjustment_meta/res in Rviz.
The error message origins in tf2 since at startup it has problems to get the static transforms supplied by the .bag file. That shouldn't be a problem however. What kind of setup file you are sourcing depends on the shell environment you are using :) However make sure that you source the file in the directory devel_limo_release !

Looking forward to your feedback :) 

Best regards,

Johannes

**Comment by MaxCCao** [comment]
Hi, so I look through your paper, and i wonder how to treat the feature points on the ground plane? It seems first you use RANSAC to fit a line, then how to estimate the depth? I'm a little bit confused :)
And I want to use your project to run on kitti dataset, so how can I output  the pose to a text file since I want to use the pose to plot a trajectory?

Looking forward to your reply
Thanks

**Comment by johannes-graeter** [comment]
The main trick is to constrain the local planes around the image features on the ground.
As contraint we use a globally estimated groundplane from the LIDAR pointcloud und punish large difference to it. The depth estimation itself is then the same as for "normal" image features f.e. on houses, etc. so we just intersect the locally estimated plane from LIDAR with the viewing ray from the camera.

For outputting the poses you have several options:
1: when you finish the program and call the destructor of the estimation node a map with all estimated landmarks and poses is dumped to /tmp (see https://github.com/johannes-graeter/limo/blob/master/keyframe_bundle_adjustment_ros_tool/src/mono_lidar/mono_lidar.cpp, line 82-84), you can ectract the poses from there and convert them to KITTI
2: Is personally just added a few lines of code writing done a text file.
3: You can write a rosnode that subscribes to tf2 and dumps the pose for each camera timestamp, which would be the cleanest solution I think.

**Comment by johannes-graeter** [comment]
A yeah keep in mind that for running on KITTI, you will need to add a semantic labeling node (in the test data provided (04.bag), I included them in the .bag as additional topic)
