### ISSUE TITLE
A question about how can point clout project into camera frame

### ISSUE THREAD

**Issue by zjlooojoe** [johannes-graeter/limo#17]
Hi,I want to ask a question about your paper,"First the LIDAR point cloud is transformed into the camera frame and projected onto the image plane. "in BLOCK S: SCALE ESTIMATION , Approach. I want to know which park of your code can work out it? Thank you

**Comment by johannes-graeter** [comment]
Thanks for your interest in my work.
The depth estimation of the image features is part of the the repo https://github.com/johannes-graeter/mono_lidar_depth.git which is installed by the install_repos.sh script.

The reprojection is done by the class https://github.com/johannes-graeter/mono_lidar_depth/blob/master/monolidar_fusion/include/monolidar_fusion/camera_pinhole.h and mostly used in the depth estimator in https://github.com/johannes-graeter/mono_lidar_depth/blob/master/monolidar_fusion/include/monolidar_fusion . 

Cheers,

Johannes

PS: Downloading the repos as in the README and loading them in a nice IDE helps a lot! :)

**Comment by zjlooojoe** [comment]
Thank you very much!! Your work is so good!!
