### ISSUE TITLE
run the demo with kitti and real data (velodye and mono)

### ISSUE THREAD

**Issue by wenjunj** [johannes-graeter/limo#21]
Hi,could you please give a guide for running the demo with kitti? I use the kitti2rosbag but I find you change something such as the frame_Id,topic name and Semantics label ! THANK YOU : )

**Comment by johannes-graeter** [comment]
Hi there,
thanks for your interest in my work. 
I created the rosbags with an own converter, that is why the topic names are different. Also I added semantic labeled images (created with a CNN). 
You find a short description here: https://github.com/johannes-graeter/limo
I know it is not very profound and I will enhance it soon. 
https://github.com/johannes-graeter/limo/blob/master/README.md
have a look at demo_keyframe_bundle_adjustment_meta/kitti_standalone.launch, most of the topics should be assigned there. 
Feel free to ask questions about the topics!
I also described some of that in this issue: #16 .

I also tested it on our vehicles, I plan to release a more detailed "How To" shortly!

Best
