### ISSUE TITLE
Some qeustions for real data (VLP-16 and Mono)

### ISSUE THREAD

**Issue by youngsikshin** [johannes-graeter/limo#24]
Hello. I'm working on a real data experiment using LIMO. I use VLP-16 and mono camera. We have confirmed that LIMO is working with our sensor configuration. However, since LiDAR has 16 beams, it is necessary to modify parameters for good performance. What parameters should I change in this case? And can I disable the label image?
I would be very helpful if you let me know some tips.

Thank you.

**Comment by johannes-graeter** [comment]
Hi,

it is super exciting, that you want to try my code on your system in real life :)
For disabling the labeled images refer to #16 . The results will then be a bit worse though depending on your scenery. 
I have never used the system with an 16 layers scanner though. 
The parameters you look for are to be found in https://github.com/johannes-graeter/limo/blob/master/demo_keyframe_bundle_adjustment_meta/res/mono_lidar_fusion_parameters.yaml (be careful that one is the messiest module of all :) ). 
Play with the pixelarea search width and height (l. 14,l. 17). They are the parameters for the roi to used for local plane extraction as described in the paper. In a first try I would double them and have a look at the depths that come out of tracklets_depth_ros_tool. 

I have a major update in the pipeline, which has tools to visualize those depths.
Please stay tuned :)

Best regards,

Johannes

**Comment by johannes-graeter** [comment]
Any news?
