### ISSUE TITLE
roslaunch Error

### ISSUE THREAD

**Issue by hcaawu** [johannes-graeter/limo#26]
When I do "roslaunch demo_keyframe_bundle_adjustment_meta kitti_stanalone.launch"
This error shows up. Any ideas?
[kitti_stanalone.launch] is neither a launch file in package [demo_keyframe_bundle_adjustment_meta] nor is [demo_keyframe_bundle_adjustment_meta] a launch file name
The traceback for the exception was written to the log file

**Comment by johannes-graeter** [comment]
Did you source your catkin workspace?
