### ISSUE TITLE
build error in ROS melodic 

### ISSUE THREAD

**Issue by vguidance** [johannes-graeter/limo#31]
Hi. 
I have followed the wiki/readme and tried to install with your provided script. But i could not get it built. I have two systems with Ubuntu 18.04, ROS melodic, opencv3.4.4, libpcl-dev 1.8.1, ceres 1.14.0. Both of my systems show same error and start failing while building the util_nodes_tf2_ros_tool.  I hope you have some time to help me to resolve it. Thank you. 

Best regards
Kawser Jahan

edit: 
However, I have used `sudo apt-get install ros-melodic-opencv-apps`, not the one for the ros kinect. 

[unittests_dump.txt](https://github.com/johannes-graeter/limo/files/3365021/unittests_dump.txt)
![Screenshot from 2019-07-06 22-59-46](https://user-images.githubusercontent.com/44556791/60761089-00031b00-a042-11e9-9622-7169c31f5c06.png)

**Comment by johannes-graeter** [comment]
Hi there,

The system is not yet ported to 18.04 and melodic but is only tested on 16.04 and kinetic. At the moment I am in the process of porting it but as you mentioned I don‘t have a lot of time:) if you want to help I would appreciate it contact me if that is the case than I can coordinate:) in the mean time you can try it out with the virtual machine I have for download in the readme ( with 16.04 and kinetic)

**Comment by johannes-graeter** [comment]
Sorry no update yet maintaining this in my freetime is quite hard :) if you would be able to help this would be much appreciated:) (write me if this is the case:)

**Comment by johannes-graeter** [comment]
I ported it to 18.04+melodic (branch port_18.04). However there is a linker error originating from opencv extras. This seems to be a proble with the standard opencv versions from melodic and bionic.A solution is to build opencv yourself. 
I suspect that the problem will be solved with the new  ubuntu version that comes in Mai
