### ISSUE TITLE
Build Error about pcl_ros

### ISSUE THREAD

**Issue by LongruiDong** [johannes-graeter/limo#32]
Hi,
thank u for sharing your excellent code !!!
But after "bash install_repos.sh" , i got this Error
```
Errors     << image_preproc_ros_tool:cmake /home/dlr/catkin_ws/logs_limo_release/image_preproc_ros_tool/build.cmake.000.log
CMake Error at /home/dlr/catkin_ws/src/mrt_cmake_modules/cmake/Modules/FindAutoDeps.cmake:80 (message):
  Package pcl_ros is specified for autodepend but cmake variables are not
  defined.  Did you resolve dependencies?
Call Stack (most recent call first):
  CMakeLists.txt:16 (find_package)

```
Can you help me solve this error?
Thanks in advance!!

**Comment by johannes-graeter** [comment]
Hi,

thanks for the interest in my code.
Seems you haven't installed pcl_ros interfaces. Did you install ros-kinetic-desktop-full as described in the README? In that case, ros_pcl should come with the installation...

Best,
Johannes
