### ISSUE TITLE
KITTI dataset to bag file

### ISSUE THREAD

**Issue by zhu-bingo** [johannes-graeter/limo#36]
how to convert KITTI dataset to bag file ?
thank you

**Comment by shaoxiaoyang** [comment]
There has already somebody done it ,please see the detail in [https://github.com/ethz-asl/kitti_to_rosbag](url) ,it may can help you .

**Comment by johannes-graeter** [comment]
Hi there, i used my own converter but the one from eth works perfectly fine. Thanks for the hint shaoxiaoyang! However be aware that you need to inculde semantic images that you need to produce yourself. Also be aware that you have to adapt topic names accordingly. If you have done I would be happy if you could share how, so we can add it to the docs:)
