### ISSUE TITLE
poses out and rviz problem

### ISSUE THREAD

**Issue by xuwuzhou** [johannes-graeter/limo#38]
Thanks for your great work!
But when I run the rviz node,there is no image presented,as listed:
![2019-12-12 21-46-09屏幕截图](https://user-images.githubusercontent.com/44218507/70717394-33508100-1d29-11ea-978e-344bdd839902.png)
![2019-12-12 21-47-50屏幕截图](https://user-images.githubusercontent.com/44218507/70717403-364b7180-1d29-11ea-876c-877a5e00f3a8.png)

and I want to know which published topic is the most accurated poses result, is the topic "/semantic_labels_nodelet_manager/bond"?

**Comment by johannes-graeter** [comment]
Hi there, sorry I was overload with work.
During corona I have more time for cleanup :)
Just merged a pull request fixing this.
Best, Johannes
