### ISSUE TITLE
deactivating semantic label

### ISSUE THREAD

**Issue by hcyoo93** [johannes-graeter/limo#39]
Thank you for great work!

I looked through previous Issues regarding this like #16, #30 

However, I don't understand the approach clearly and I tried different way.

It looks fine, but I want to check if it is correct and share this.

1. kitti_standalone.launch
Line 52 
`<include file="$(find demo_keyframe_bundle_adjustment_meta)/launch/semantic_labels.launch"/>`

to

`<!-- include file="$(find demo_keyframe_bundle_adjustment_meta)/launch/semantic_labels.launch"/ -->`

2. keyframe_ba_monolid.launch
Line 4
`<arg name="tracklets_subscriber_topic" default="/tracklets_depth/tracklets/left/with_outlier_label"/>`

to

`<arg name="tracklets_subscriber_topic" default="/tracklets_depth/tracklets/left/with_outlier_dummy"/>`

For number2, I didn't get any issue when I ran the code, but as I said above

I want to get a check from others

Thank you

**Comment by johannes-graeter** [comment]
Yes thats the way, matches get a label of -1 per default which means "ignore label" so if the semantic_label node does not overwrite these, the keyframe_ba_monolid node will treat them independanlty of semantics. The results are dumped to the dump_path, specified in keyframe_ba_monolid.launch, line 59. Per default this is /tmp/poses_dump.txt

If the performance is not good enough, play around with the threshold parameters in keyframe_ba_monolid node and share your results :) I used that on our autonomous vehicle but never tuned it on KITTI :)
