### ISSUE TITLE
How to estimate the result

### ISSUE THREAD

**Issue by hcyoo93** [johannes-graeter/limo#40]
Thank you for your great work!

I wonder how to estimate the result after run this code.

As far as I know, estimated pose result is saved in forms of "test.txt" so that it can be run with kitti devkit_odometry

However, I cannot find anything after the sequence is done.

I guess, there should be something I miss.

Please share your experience!

Thank you

**Comment by johannes-graeter** [comment]
As described, the results are saved in  a txt file that is defined by a topic in keyframe_ba_monolid.launch, by default it is /tmp/poses_dump.txt
