### ISSUE TITLE
Why are there so many grammatical errors?

### ISSUE THREAD

**Issue by QiangLiuSJTU** [johannes-graeter/limo#55]
/home/qiangliu/catakin_limo/src/rosinterface_handler/include/rosinterface_handler/utilities.hpp:314:13: error: expected primary-expression before ‘...’ token
     (oss << ... << std::forward<Args>(Args_));
             ^
/home/qiangliu/catakin_limo/src/rosinterface_handler/include/rosinterface_handler/utilities.hpp:314:13: error: expected ‘)’ before ‘...’ token

/home/qiangliu/catakin_limo/src/rosinterface_handler/test/src/test_smart_subscriber.cpp:17:56: error: cannot call member function ‘void TestNode::smartMsgCallback(const ConstPtr&)’ without object
         smartSub.registerCallback([this](auto&& msg) { smartMsgCallback(msg); });

**Comment by johannes-graeter** [comment]
Hi,

thanks a lot for your interest in my work.
Closing the issue means it is solved? The issues where caused by an external library (rosinterface_handler)...

Best,
Johannes
