### ISSUE TITLE
no image recieved

### ISSUE THREAD

**Issue by OuFang** [johannes-graeter/limo#61]
Hi,
 thank you for your work and there is a question about it.  When I run the command "rviz -d ${your_catkin_workspace}/src/demo_keyframe_bundle_adjustment_meta/res/default.rviz" ,the waring "no image recived" displayed on rviz. I think maybe some wrong with the data 04.bag that I download.when I use "rosbag info 04.bag" ,there are 4 topics not include image topic.Could you give me detail rosbag info,or provide other  download method?Thank you very much.

**Comment by johannes-graeter** [comment]
This seems to work for most, if you still have a problem with that plz reopen
