### ISSUE TITLE
Bulid Problem

### ISSUE THREAD

**Issue by yanlong658** [johannes-graeter/limo#62]
Hello

Your work is very nice.
However, I have some question about the build.
I do my best to deal with it but I don't any ideal.
Could you help me ?
![image](https://user-images.githubusercontent.com/37499691/127617575-308d0976-03fb-4836-bdea-aec543c523b7.png)

Thank you

**Comment by LongruiDong** [comment]
> Hello
> 
> Your work is very nice. However, I have some question about the build. I do my best to deal with it but I don't any ideal. Could you help me ? ![image](https://user-images.githubusercontent.com/37499691/127617575-308d0976-03fb-4836-bdea-aec543c523b7.png)
> 
> Thank you

i am the same with you. Have u solved yet?

**Comment by LongruiDong** [comment]
> Hello
> 
> Your work is very nice. However, I have some question about the build. I do my best to deal with it but I don't any ideal. Could you help me ? ![image](https://user-images.githubusercontent.com/37499691/127617575-308d0976-03fb-4836-bdea-aec543c523b7.png)
> 
> Thank you

here is an answer from author:

https://github.com/johannes-graeter/limo/issues/63#issuecomment-963084494

**Comment by tonywong-1115** [comment]
> > Hello
> > Your work is very nice. However, I have some question about the build. I do my best to deal with it but I don't any ideal. Could you help me ? ![image](https://user-images.githubusercontent.com/37499691/127617575-308d0976-03fb-4836-bdea-aec543c523b7.png)
> > Thank you
> 
> here is an answer from author:
> 
> [#63 (comment)](https://github.com/johannes-graeter/limo/issues/63#issuecomment-963084494)

Sorry, could u be more specific where can I find the jupyter related stuff that I should comment out?  THX!

**Comment by johannes-graeter** [comment]
in https://github.com/johannes-graeter/limo/blob/master/docker/src/Dockerfile lines 84 and 85 also consider the internet connection related issues that are mentioned more below in the linked issue.
