### ISSUE TITLE
get error of tracklet_depth_node-3

### ISSUE THREAD

**Issue by aicarmark** [johannes-graeter/limo#7]
when start running, got error as below:

Got the camera info:
img_width: 1226
img_height: 370
focal_length_x: 707.091
principalPointX: 601.887
principalPointY: 183.11

Initialize DepthEstimator Post
DepthEstimator successful initialized
===============================================================================**=REQUIRED process [tracklet_depth_node-3] has died!
process has died [pid 23803, exit code -11, cmd /home/carmark/SLAM/limo-slam/devel_limo_release/lib/tracklets_depth_ros_tool/tracklet_depth_node __name:=tracklet_depth_node __log:=/home/carmark/.ros/log/ee4ed292-c0d5-11e8-848d-9cb6d0f8f3e7/tracklet_depth_node-3.log].
log file: /home/carmark/.ros/log/ee4ed292-c0d5-11e8-848d-9cb6d0f8f3e7/tracklet_depth_node-3*.log
Initiating shutdown!**
================================================================================
[mono_lidar-17] killing on exit
[semantic_labels-16] killing on exit
[label_dilation-15] killing on exit
[add_outlier_flag-14] killing on exit
[transform_local_cs_camera_gt-13] killing on exit
[transform_vehicle_camera_vehicle_gt-12] killing on exit
[transform_local_cs-11] killing on exit
[transform_local_estimate_prior-10] killing on exit
[transform_local_cs_left_camera_estimate_prior-9] killing on exit
[transform_vehicle_left_camera_estimate_prior-8] killing on exit
[ INFO] [1537888640.489776084, 0.528613523]: Duration feature matching and tracking: 71 ms
[transform_local_cs_vehcile_estimate-7] killing on exit
[transform_vehicle_left_camera_estimate-6] killing on exit
[viso_feature_tracking_node_left-2] killing on exit
[tf2_static_alias_vehicle_to_rig_left_estimate-4] killing on exit
[tf2_static_alias_vehicle_to_rig_right_estimate-5] killing on exit
[tracklet_depth_node-3] killing on exit
[gamma_correction_node_left-1] killing on exit
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
--------------------------------------
Dumped map to /tmp/mono_lidar_map_dump.yaml--------------------------------------

shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by johannes-graeter** [comment]
Hi there,

thanks for trying out this stack.
This seems to be a parallel computing problem, which is kind of hard to track...
Lets give it a try ;)
Have you tried running it in the vm I supplied (as described in the README.md)?
Next step would be to turn on debug info for this node (substitute "info" with "debug" in line 21 in file https://github.com/johannes-graeter/limo/blob/master/demo_keyframe_bundle_adjustment_meta/launch/kitti_standalone.launch).

I introduced some parallel computing to make it faster, 2 weeks ago.
You could try the old version, checking out this commit (https://github.com/johannes-graeter/limo/commit/d40600518ef6585b47f68773af5e72955e7dcdc0).

Thanks for your effort. Keep me updated!

Regards,

Johannes

**Comment by aicarmark** [comment]
@johannes-graeter 
I checkout 
[d40600518ef6585b47f68773af5e72955e7dcdc0](https://github.com/johannes-graeter/limo/commit/d40600518ef6585b47f68773af5e72955e7dcdc0)
[4b3f6f38792c50417ae501ba00c33db87704a706](https://github.com/johannes-graeter/mono_lidar_depth/commit/4b3f6f38792c50417ae501ba00c33db87704a706)

got same erros

Initialize DepthEstimator Post
DepthEstimator successful initialized
[ INFO] [1537942026.394675088, 0.524007758]: Duration feature matching and tracking: 34 ms
================================================================================REQUIRED process [tracklet_depth_node-3] has died!
process has died [pid 19060, exit code -11, cmd /home/carmark/SLAM/limo-slam/devel_limo_release/lib/tracklets_depth_ros_tool/tracklet_depth_node __name:=tracklet_depth_node __log:=/home/carmark/.ros/log/a3422cbc-c14e-11e8-a97e-9cb6d0f8f3e7/tracklet_depth_node-3.log].
log file: /home/carmark/.ros/log/a3422cbc-c14e-11e8-a97e-9cb6d0f8f3e7/tracklet_depth_node-3*.log
Initiating shutdown!
================================================================================
[semantic_labels-16] killing on exit
[mono_lidar-17] killing on exit
[label_dilation-15] killing on exit
[add_outlier_flag-14] killing on exit
[transform_local_cs_camera_gt-13] killing on exit
[transform_vehicle_camera_vehicle_gt-12] killing on exit
[transform_local_cs-11] killing on exit
[transform_local_estimate_prior-10] killing on exit
[transform_vehicle_left_camera_estimate_prior-8] killing on exit
[transform_local_cs_left_camera_estimate_prior-9] killing on exit
[transform_local_cs_vehcile_estimate-7] killing on exit
[transform_vehicle_left_camera_estimate-6] killing on exit
--------------------------------------
Dumped map to /tmp/mono_lidar_map_dump.yaml--------------------------------------

**Comment by johannes-graeter** [comment]
please turn verbosity to debug as described in the last comment. 
Like that I can not see at what point the method fails.

Also try the virtual machine please.

**Comment by johannes-graeter** [comment]
I forgot to add the nodelet_plugins file in that prjoect (see https://github.com/johannes-graeter/limo/issues/8)
pull mono_lidar_depth and try again please :)

**Comment by johannes-graeter** [comment]
Hi there,

did it work? I would like to close the issue.
