### ISSUE TITLE
demo does not use GPU

### ISSUE THREAD

**Issue by Abdob** [johannes-graeter/limo#72]
when launching 

```
roslaunch demo_keyframe_bundle_adjustment_meta kitti_standalone.launch 
```

The gpu doesn't get used, nvidia-smi doesn't show any processes uses compute

Are we expecting CUDA to accelerate this demo?

**Comment by johannes-graeter** [comment]
Hi no at the moment this runs solely on cpu (except for the semantic segmentation of course which is computed beforehand in this case.)
