### ISSUE TITLE
Reproducing results for sequence 1

### ISSUE THREAD

**Issue by Abdob** [johannes-graeter/limo#74]
Using the bag file for sequence one, getting the pose result and plotting on matlab I get this:
![image](https://user-images.githubusercontent.com/8084476/184260413-45b3fd27-f87e-4c21-b3ac-e8629957b338.png)

our results the rover traveled around 100+meters but the plot shows otherwise:

![image](https://user-images.githubusercontent.com/8084476/184260573-5ce39166-1810-470a-8a76-d1244128744a.png)

**Comment by Abdob** [comment]
I'm trying a more powerful PC and proper plotting, this is what I get:
![seq_1_rate_01](https://user-images.githubusercontent.com/8084476/184509232-21b6a009-c5b1-4e6e-b240-bfb7911da379.jpg)

**Comment by Abdob** [comment]
When increasing the rate to 0.125 12 samples go missing, in both cases the odometry becomes dense towards the end
![seq_1_rate_0125](https://user-images.githubusercontent.com/8084476/184509793-87bf7a75-fe0a-48df-8b80-fb2d0b617e75.jpg)

At around sample 200/1100 X and Z level off, this hiccup can be seen when plotting sample number vs X or Z

**Comment by Abdob** [comment]
I get some improvements when configuring the odometry application by uncommenting the catkin config related lines in the dockerfile
![seq_1_rate_01_app_release_build](https://user-images.githubusercontent.com/8084476/184510816-a02fdbb9-f5a1-45b6-a1fa-470539b391ef.jpg)
![seq_1_rate_01_app_release_build_XZ_over_Samples](https://user-images.githubusercontent.com/8084476/184510847-95894b9e-5d44-41c4-8648-437789fc78bd.jpg)

Now, at near sample 500 the XZ trajectory is leveling off..

**Comment by johannes-graeter** [comment]
not reproducable so closing
