### ISSUE TITLE
build error with ros melodic

### ISSUE THREAD

**Issue by Huyhust13** [johannes-graeter/limo#75]
Dear,
I faced some error when compile this project in ros melodic. It cause nodelet different from kinetic to melodic.
I found out solution from this link: https://github.com/KumarRobotics/msckf_vio/issues/69
Finally, it works!

**Comment by johannes-graeter** [comment]
awesome! would be great if you could add this change and file a pull request to contribute. In order to maintain compatibilty with kinetic you would need to detect if its a kinetic or melodic build though...

Best Johannes

**Comment by Huyhust13** [comment]
> awesome! would be great if you could add this change and file a pull request to contribute. In order to maintain compatibilty with kinetic you would need to detect if its a kinetic or melodic build though...
> 
> Best Johannes

There is already pull request: https://github.com/KIT-MRT/feature_tracking/pull/1/commits/8066fdce1b585bc5d25e25baed58a8f71b3d6433

**Comment by johannes-graeter** [comment]
So PLUGIN_EXPORT_CLASS works in both melodic and kinetic correct?

**Comment by Huyhust13** [comment]
I didn't test it in kinetic :D
