### ISSUE TITLE
Hi,I meet with this problem by using"docker-compose build"

### ISSUE THREAD

**Issue by rodrickcui** [johannes-graeter/limo#79]
Unsupported config option for services.limo: 'runtime'
How to solve it?
the content of docker-compose.yml is 
version: '3.4'

services:
  limo:
    container_name: limo
    build:
      context: ./src
    image: ros:melodic-perception
    ports:
      - 8888:8888
    network_mode: host
    ipc: host
    privileged: true  
    runtime: nvidia

**Comment by rodrickcui** [comment]
solved

**Comment by y-l-a** [comment]
Hi! I have also encountered this problem. How did you solve it?

**Comment by johannes-graeter** [comment]
did you install the nvidia-runtime? https://stackoverflow.com/questions/69995187/docker-compose-unsupported-config-option-for-runtime
 NOt sure if the image the container is based on (ros:melodic-perception) now uses gpu support...
