### ISSUE TITLE
Package viso_feature_tracking was not found.

### ISSUE THREAD

**Issue by MaJirui** [johannes-graeter/limo#84]
Package viso_feature_tracking was not found.  If it is a catkin package:
  Make sure it is present.  If it is an external package: Make sure it is
  listed in mrt_cmake_modules/yaml/cmake.yaml!

**Comment by karthikbolla** [comment]
Did your issue get resolved? I was facing the same problem.

**Comment by johannes-graeter** [comment]
Hi there,
guess KIT-MRT deleted the repos from their workspace. I changed the script so that it points to my custom forks of these projects.

Note however that the project is under heavy reconstruction (for which I only rarely find time)...

**Comment by qlsinori** [comment]
I still met this problem, can anybody give me some advice?
